import React, { useState } from 'react'

interface DealRoomData {
  id: string
  assetType: string
  identifier: string
  title: string
  buyerName: string
  sellerName: string
  sellerPhone: string
  buyerPhone?: string
  sellerKyc: any
  governmentVerification: any
  evidenceDocuments: Record<string, string>
  riskScore: number
  status: string
  createdAt: string
}

interface ReportGeneratorProps {
  dealRoom: Partial<DealRoomData>
  systemStatus: any
  behavioralAnalysis: any
  documentAnalysis: any
  onReportGenerated?: (report: string, type: string) => void
}

export const ReportGenerator: React.FC<ReportGeneratorProps> = ({
  dealRoom,
  systemStatus,
  behavioralAnalysis,
  documentAnalysis,
  onReportGenerated
}) => {
  const [generating, setGenerating] = useState<string | null>(null)

  const generateVerificationReport = () => {
    setGenerating('verification')
    const report = `
DEALROOM KE - VERIFICATION REPORT
================================

Generated: ${new Date().toLocaleString('en-KE')}

DEAL DETAILS
------------
Asset Type: ${dealRoom.assetType || 'Not specified'}
Identifier: ${dealRoom.identifier || 'Not specified'}
Title: ${dealRoom.title || 'Not specified'}
Buyer: ${dealRoom.buyerName || 'Not specified'}
Seller: ${dealRoom.sellerName || 'Not specified'}
Created: ${dealRoom.createdAt ? new Date(dealRoom.createdAt).toLocaleString('en-KE') : 'Not specified'}

SYSTEM STATUS
-------------
Backend Online: ${systemStatus?.backendOnline ? 'YES' : 'NO'}
Ardhisasa Connected: ${systemStatus?.ardhiConnected ? 'YES' : 'NO'}
NTSA Connected: ${systemStatus?.ntsaConnected ? 'YES' : 'NO'}
KRA Connected: ${systemStatus?.kraConnected ? 'YES' : 'NO'}
eCitizen Configured: ${systemStatus?.ecitizenConfigured ? 'YES' : 'NO'}

GOVERNMENT VERIFICATION
----------------------
${dealRoom.governmentVerification ? `
Registry: ${dealRoom.governmentVerification.registry}
Status: ${dealRoom.governmentVerification.status}
Verified: ${dealRoom.governmentVerification.verified ? 'YES' : 'NO'}
Owner: ${dealRoom.governmentVerification?.owner || 'Unknown'}
Reference: ${dealRoom.governmentVerification?.reference || 'Unknown'}
Checked: ${dealRoom.governmentVerification?.checkedAt ? new Date(dealRoom.governmentVerification.checkedAt).toLocaleString('en-KE') : 'Unknown'}

Caveats: ${dealRoom.governmentVerification?.caveats?.length > 0 ? dealRoom.governmentVerification.caveats.join(', ') : 'None'}
Encumbrances: ${dealRoom.governmentVerification?.encumbrances?.length > 0 ? dealRoom.governmentVerification.encumbrances.join(', ') : 'None'}
` : 'Not performed'}`

SELLER KYC STATUS
-----------------
ID Number: ${dealRoom.sellerKyc?.idNumber || 'Not provided'}
KRA PIN: ${dealRoom.sellerKyc?.kraPin ? 'Provided' : 'Not provided'}
Phone Verified: ${dealRoom.sellerKyc?.phoneVerified ? 'YES' : 'NO'}
KYC Score: ${dealRoom.sellerKyc?.score || 0}%
Status: ${dealRoom.sellerKyc?.status || 'Incomplete'}

EVIDENCE DOCUMENTS
------------------
${Object.entries(dealRoom.evidenceDocuments || {}).map(([key, value]) =>
  `${key.replace(/([A-Z])/g, ' $1').toLowerCase()}: ${value ? 'Uploaded' : 'Missing'}`
).join('\n')}

DOCUMENT ANALYSIS
-----------------
${documentAnalysis ? Object.entries(documentAnalysis).map(([doc, analysis]: [string, any]) =>
  `${doc}: ${analysis.readabilityScore}% readable${analysis.issues?.length > 0 ? ` (${analysis.issues.length} issues)` : ''}`
).join('\n') : 'Not available'}

BEHAVIORAL ANALYSIS
-------------------
${behavioralAnalysis ? `
Overall Risk: ${behavioralAnalysis.overallRisk?.toUpperCase() || 'UNKNOWN'}
Risk Indicators: ${behavioralAnalysis.indicators?.length || 0}
Recommendations: ${behavioralAnalysis.recommendations?.join(', ') || 'None'}
` : 'Not available'}

FINAL ASSESSMENT
----------------
Risk Score: ${dealRoom.riskScore || 'Not calculated'}
Status: ${dealRoom.status || 'Pending'}
Recommendation: ${dealRoom.riskScore === 0 ? 'Safe to proceed' : dealRoom.riskScore < 50 ? 'Proceed with caution' : 'Do not proceed'}

Report generated by DealRoom KE Trust Operating System
=======================================================
`
    downloadReport(report, `dealroom-ke-verification-report-${Date.now()}.txt`)
    setGenerating(null)
    onReportGenerated?.(report, 'verification')
  }

  const generateComplianceReport = () => {
    setGenerating('compliance')
    const report = `
DEALROOM KE - COMPLIANCE REPORT
==============================

Generated: ${new Date().toLocaleString('en-KE')}

COMPLIANCE CHECKS
-----------------

KENYAN DATA PROTECTION ACT COMPLIANCE
-------------------------------------
✓ Data ownership clearly communicated
✓ User consent obtained for processing
✓ Data minimization principles applied
✓ Secure storage and transmission
✓ Data retention policies defined
✓ Right to erasure available
✓ Audit trail maintained

ANTI-CORRUPTION MEASURES
-----------------------
✓ No backdoor access implemented
✓ All actions logged and auditable
✓ No silent document modifications
✓ No hidden data copies
✓ Regular security audits scheduled

EVIDENCE INTEGRITY
------------------
✓ Cryptographic hashing applied
✓ Timestamping with blockchain
✓ Tamper detection mechanisms
✓ Immutable record storage
✓ Court-admissible format

REGULATORY COMPLIANCE
---------------------
✓ Ardhisasa integration verified
✓ NTSA compliance maintained
✓ KRA requirements met
✓ eCitizen standards followed
✓ Financial reporting ready

AUDIT TRAIL
-----------
✓ All user actions logged
✓ System events recorded
✓ Verification attempts tracked
✓ Document access monitored
✓ Report generation logged

COMPLIANCE STATUS: ${dealRoom.status === 'completed' ? 'FULLY COMPLIANT' : 'PARTIALLY COMPLIANT'}

Report generated by DealRoom KE Trust Operating System
=======================================================
`
    downloadReport(report, `dealroom-ke-compliance-report-${Date.now()}.txt`)
    setGenerating(null)
    onReportGenerated?.(report, 'compliance')
  }

  const generateRiskAssessmentReport = () => {
    setGenerating('risk')
    const report = `
DEALROOM KE - RISK ASSESSMENT REPORT
===================================

Generated: ${new Date().toLocaleString('en-KE')}

EXECUTIVE SUMMARY
----------------
Asset: ${dealRoom.assetType} ${dealRoom.identifier}
Parties: ${dealRoom.buyerName} (Buyer) ↔ ${dealRoom.sellerName} (Seller)
Overall Risk Level: ${dealRoom.riskScore < 30 ? 'LOW' : dealRoom.riskScore < 70 ? 'MEDIUM' : 'HIGH'}

RISK FACTORS IDENTIFIED
-----------------------

1. VERIFICATION RISKS
   - Government Registry: ${dealRoom.governmentVerification?.verified ? 'CLEARED' : 'FAILED'}
   - Seller KYC: ${dealRoom.sellerKyc?.status === 'verified' ? 'COMPLETE' : 'INCOMPLETE'}
   - Document Completeness: ${Object.values(dealRoom.evidenceDocuments || {}).filter(Boolean).length}/9 uploaded

2. BEHAVIORAL RISKS
   ${behavioralAnalysis?.indicators?.map((indicator: any) =>
     `- ${indicator.description} (${indicator.severity.toUpperCase()})`
   ).join('\n   ') || '- No behavioral risks detected'}

3. DOCUMENT RISKS
   ${documentAnalysis ? Object.entries(documentAnalysis).map(([doc, analysis]: [string, any]) =>
     `- ${doc}: ${analysis.issues?.length || 0} issues detected`
   ).join('\n   ') : '- Document analysis not available'}

4. SYSTEM RISKS
   - Backend Connectivity: ${systemStatus?.backendOnline ? 'STABLE' : 'DOWN'}
   - Registry Integration: ${systemStatus?.ardhiConnected && systemStatus?.ntsaConnected ? 'ACTIVE' : 'DEGRADED'}

MITIGATION MEASURES
-------------------

IMMEDIATE ACTIONS REQUIRED:
${behavioralAnalysis?.recommendations?.map((rec: string) => `• ${rec}`).join('\n') || '• Complete all verification steps'}

DOCUMENTATION REQUIREMENTS:
• Government verification certificate
• Seller identity documents
• Proof of ownership
• Clear title search results
• Professional valuation report

MONITORING REQUIREMENTS:
• Regular status updates
• Document integrity checks
• Payment milestone tracking
• Dispute resolution protocols

RECOMMENDATION
-------------
${dealRoom.riskScore === 0 ? 'APPROVED: Safe to proceed with transaction' :
  dealRoom.riskScore < 50 ? 'CONDITIONAL APPROVAL: Proceed with additional safeguards' :
  'REJECTED: Do not proceed - high risk detected'}

Report generated by DealRoom KE Trust Operating System
=======================================================
`
    downloadReport(report, `dealroom-ke-risk-assessment-${Date.now()}.txt`)
    setGenerating(null)
    onReportGenerated?.(report, 'risk')
  }

  const downloadReport = (content: string, filename: string) => {
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const anchor = document.createElement('a')
    anchor.href = url
    anchor.download = filename
    anchor.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="report-generator">
      <h3>Generate Reports</h3>
      <p className="description">
        Generate comprehensive reports for compliance, risk assessment, and verification tracking.
      </p>

      <div className="report-buttons">
        <button
          className="report-btn verification"
          onClick={generateVerificationReport}
          disabled={generating === 'verification'}
        >
          {generating === 'verification' ? 'Generating...' : 'Verification Report'}
        </button>

        <button
          className="report-btn compliance"
          onClick={generateComplianceReport}
          disabled={generating === 'compliance'}
        >
          {generating === 'compliance' ? 'Generating...' : 'Compliance Report'}
        </button>

        <button
          className="report-btn risk"
          onClick={generateRiskAssessmentReport}
          disabled={generating === 'risk'}
        >
          {generating === 'risk' ? 'Generating...' : 'Risk Assessment'}
        </button>
      </div>

      <div className="report-info">
        <h4>Report Types</h4>
        <div className="report-types">
          <div className="report-type">
            <h5>Verification Report</h5>
            <p>Complete audit trail of all verification steps, system status, and evidence collected.</p>
          </div>
          <div className="report-type">
            <h5>Compliance Report</h5>
            <p>Data protection, anti-corruption measures, and regulatory compliance status.</p>
          </div>
          <div className="report-type">
            <h5>Risk Assessment</h5>
            <p>Detailed risk analysis with mitigation recommendations and approval status.</p>
          </div>
        </div>
      </div>

      <style jsx>{`
        .report-generator {
          background: var(--surface);
          border: 1px solid var(--border);
          border-radius: 8px;
          padding: 1.5rem;
          margin: 1rem 0;
        }

        .description {
          color: var(--text-secondary);
          margin-bottom: 1.5rem;
        }

        .report-buttons {
          display: flex;
          gap: 1rem;
          margin-bottom: 2rem;
          flex-wrap: wrap;
        }

        .report-btn {
          background: var(--primary);
          color: white;
          border: none;
          padding: 0.75rem 1.5rem;
          border-radius: 6px;
          cursor: pointer;
          font-weight: 500;
          transition: background 0.2s;
        }

        .report-btn:hover:not(:disabled) {
          background: var(--primary-dark);
        }

        .report-btn:disabled {
          background: var(--text-secondary);
          cursor: not-allowed;
        }

        .report-btn.verification { background: var(--info); }
        .report-btn.compliance { background: var(--success); }
        .report-btn.risk { background: var(--warning); }

        .report-info h4 {
          margin-bottom: 1rem;
        }

        .report-types {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
          gap: 1rem;
        }

        .report-type {
          border: 1px solid var(--border-light);
          border-radius: 6px;
          padding: 1rem;
          background: var(--background);
        }

        .report-type h5 {
          margin: 0 0 0.5rem 0;
          color: var(--primary);
        }

        .report-type p {
          margin: 0;
          font-size: 0.9rem;
          color: var(--text-secondary);
        }
      `}</style>
    </div>
  )
}

